# Netscape HTTP Cookie File
# https://curl.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_localhost	FALSE	/	FALSE	0	session	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsImlhdCI6MTc4NDkxMTYyOCwiZXhwIjoxNzg0OTU0ODI4fQ.JE_2i0IV_UzBbw8WLCO8bb1XwtXxkUEexFRnj3weDuo
