# Netscape HTTP Cookie File
# https://curl.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_localhost	FALSE	/	FALSE	0	session	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsImlhdCI6MTc4NTEwOTY1NiwiZXhwIjoxNzg1MTUyODU2fQ.9LQQIBB4KcHV6VjTFcs_AC-pJaqjaXWEQ3lDd6qwyaY
