# Netscape HTTP Cookie File
# https://curl.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_localhost	FALSE	/	FALSE	0	session	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsImlhdCI6MTc4NDk0OTcwNywiZXhwIjoxNzg0OTkyOTA3fQ.cZT5Hvreo5OgJjOsGJNM0pnwx3DN9-uAhJGouccBYZE
