# Netscape HTTP Cookie File
# https://curl.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_localhost	FALSE	/	FALSE	0	session	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjMsImlhdCI6MTc4NDkxMTYyOCwiZXhwIjoxNzg0OTU0ODI4fQ.KHCMp2QNJd4-QQL4YbpCy1NM83s5kzW0hbHQQr8cqlk
