# Netscape HTTP Cookie File
# https://curl.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_localhost	FALSE	/	FALSE	0	session	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjIsImlhdCI6MTc4NTExOTYyNCwiZXhwIjoxNzg1MTYyODI0fQ.tQynJkZ5AOA_MpyrIuFised21VsIRlpxDa0Rgpm7v8g
