# Netscape HTTP Cookie File
# https://curl.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_localhost	FALSE	/	FALSE	0	session	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjIsImlhdCI6MTc4NDkxNDk2MCwiZXhwIjoxNzg0OTU4MTYwfQ.NzCz8mKrZkjuGfoF7ung3CmBYG08nFNCJRLtTfNkTTI
