# Netscape HTTP Cookie File
# https://curl.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_localhost	FALSE	/	FALSE	0	session	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjIsImlhdCI6MTc4NDk0OTcwNywiZXhwIjoxNzg0OTkyOTA3fQ.2YKR8kEuAniEKbwM55nH2U3X9g66JZJ6HmDl6tUYUEc
